language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Lwad06S8bh3Zr/OrEy/WunUxdlPgtwMB9Q0kUTCa/p3Bq1s54G7SXJIBH7AOl2vq3Dr9vIrNzBzZhWwgR7z0ugbhnsNQHugAGrbok5kVF712hhQa5ZAHB09MPOocfPQAv+8Qx3Hz5i+J8ZCRd9Vc9xV+jpkPg3cxqCeFRWwt4+HGMOeoowQJbRAEbkmB9MAPYaHTk+8qbRzSR5zpRjR0T1Ui6PLBD2DJuFm1xut9ZnW7JjIGp9Q5ekO28dSODC1ltwFHZfPIRpYP+Rz2goY6qtBOzFQ2Br9xuOPs7y9huHfVh9CPOAgbeOepuawUpZPJcLN/21AZf6lFEeRsOrZ8tJqvoRKjhnMvGrUW+1dbcr0T56OWFQvrlUKJRHJTEOiNdMRFAR67l4OrIc/dbcxus1/NuQ8cC73kap7lKtvWOan2cF2XDKMcFzXPKQ3URzMATkbBCFFyl5w/uMS3h+ijxfZ3E1zJdFlWcHTal5Lcdbn9lbBqRORyk8aW8hVikGUcTSmnVhTQTJofx356HRDAHaF1U/2ssIQku9M/HHUp3T07NIhp+wtx6TkeDi6PZqbbNmqxbvnDwRiAYJJiNC/a4lCt+bxtGWgjos2KgKjSRd7pzwhq+S2rmFps2KxTwmKZMZB4TjJp8eOoMPSwCISIZ/R9DWq98Jcf+RVMrBhCRwk=
  file:
    - "rehype-raw.js"
    - "rehype-raw.min.js"
  on:
    tags: true
